language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("DataArrays");'
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'Pkg.test("DataArrays", coverage=true)'; fi
  - if [ $TRAVIS_JULIA_VERSION = "release" ]; then julia -e 'Pkg.test("DataArrays")'; fi
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("DataArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
